name: Code Coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libfuse-dev protobuf-compiler
      - name: Test with coverage
        run: cargo test --all
